// --------------------------------------------------------------------
// Copyright (c) 2010 by Terasic Technologies Inc. 
// --------------------------------------------------------------------
//
// Permission:
//
//   Terasic grants permission to use and modify this code for use
//   in synthesis for all Terasic Development Boards and Altera Development 
//   Kits made by Terasic.  Other use of this code, including the selling 
//   ,duplication, or modification of any portion is strictly prohibited.
//
// Disclaimer:
//
//   This VHDL/Verilog or C/C++ source code is intended as a design reference
//   which illustrates how these types of functions can be implemented.
//   It is the user's responsibility to verify their design for
//   consistency and functionality through the use of formal
//   verification methods.  Terasic provides no warranty regarding the use 
//   or functionality of this code.
//
// --------------------------------------------------------------------
//           
//                     Terasic Technologies Inc
//                     356 Fu-Shin E. Rd Sec. 1. JhuBei City,
//                     HsinChu County, Taiwan
//                     302
//
//                     web: http://www.terasic.com/
//                     email: support@terasic.com
//
// --------------------------------------------------------------------
//
// Major Functions:	DE2_115 D5M+VGA 640*480 800*600 solution
//
// --------------------------------------------------------------------
//
// Revision History :
// --------------------------------------------------------------------
//   Ver  :| Author            :| Mod. Date :| Changes Made:
//   V1.0 :| Johnny FAN Peli Li:| 22/07/2010:| Initial Revision
// --------------------------------------------------------------------
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================
//to set the VGA solution
`include "VGA_Param.h" 

module DE2_115_CAMERA(

	//////////// CLOCK //////////
	CLOCK_50,
	CLOCK2_50,
	CLOCK3_50,

	//////////// Sma //////////
	SMA_CLKIN,
	SMA_CLKOUT,

	//////////// LED //////////
	LEDG,
	LEDR,

	//////////// KEY //////////
	KEY,

	//////////// EJTAG //////////
	EX_IO,

	//////////// SW //////////
	SW,

	//////////// SEG7 //////////
	HEX0,
	HEX1,
	HEX2,
	HEX3,
	HEX4,
	HEX5,
	HEX6,
	HEX7,

	//////////// LCD //////////
	LCD_BLON,
	LCD_DATA,
	LCD_EN,
	LCD_ON,
	LCD_RS,
	LCD_RW,

	//////////// RS232 //////////
	UART_CTS,
	UART_RTS,
	UART_RXD,
	UART_TXD,

	//////////// PS2 for Keyboard and Mouse //////////
	PS2_CLK,
	PS2_CLK2,
	PS2_DAT,
	PS2_DAT2,

	//////////// SDCARD //////////
	SD_CLK,
	SD_CMD,
	SD_DAT,
	SD_WP_N,

	//////////// VGA //////////
	VGA_B,
	VGA_BLANK_N,
	VGA_CLK,
	VGA_G,
	VGA_HS,
	VGA_R,
	VGA_SYNC_N,
	VGA_VS,

	//////////// Audio //////////
	AUD_ADCDAT,
	AUD_ADCLRCK,
	AUD_BCLK,
	AUD_DACDAT,
	AUD_DACLRCK,
	AUD_XCK,

	//////////// I2C for EEPROM //////////
	EEP_I2C_SCLK,
	EEP_I2C_SDAT,

	//////////// I2C for Audio Tv-Decoder  //////////
	I2C_SCLK,
	I2C_SDAT,

	//////////// Ethernet 0 //////////
	ENET0_GTX_CLK,
	ENET0_INT_N,
	ENET0_LINK100,
	ENET0_MDC,
	ENET0_MDIO,
	ENET0_RST_N,
	ENET0_RX_CLK,
	ENET0_RX_COL,
	ENET0_RX_CRS,
	ENET0_RX_DATA,
	ENET0_RX_DV,
	ENET0_RX_ER,
	ENET0_TX_CLK,
	ENET0_TX_DATA,
	ENET0_TX_EN,
	ENET0_TX_ER,
	ENETCLK_25,

	//////////// Ethernet 1 //////////
	ENET1_GTX_CLK,
	ENET1_INT_N,
	ENET1_LINK100,
	ENET1_MDC,
	ENET1_MDIO,
	ENET1_RST_N,
	ENET1_RX_CLK,
	ENET1_RX_COL,
	ENET1_RX_CRS,
	ENET1_RX_DATA,
	ENET1_RX_DV,
	ENET1_RX_ER,
	ENET1_TX_CLK,
	ENET1_TX_DATA,
	ENET1_TX_EN,
	ENET1_TX_ER,

	//////////// TV Decoder //////////
	TD_CLK27,
	TD_DATA,
	TD_HS,
	TD_RESET_N,
	TD_VS,

	//////////// USB 2.0 OTG //////////
	OTG_ADDR,
	OTG_CS_N,
	OTG_DACK_N,
	OTG_DATA,
	OTG_DREQ,
	OTG_FSPEED,
	OTG_INT,
	OTG_LSPEED,
	OTG_RD_N,
	OTG_RST_N,
	OTG_WE_N,

	//////////// IR Receiver //////////
	IRDA_RXD,

	//////////// SDRAM //////////
	DRAM_ADDR,
	DRAM_BA,
	DRAM_CAS_N,
	DRAM_CKE,
	DRAM_CLK,
	DRAM_CS_N,
	DRAM_DQ,
	DRAM_DQM,
	DRAM_RAS_N,
	DRAM_WE_N,

	//////////// SRAM //////////
	SRAM_ADDR,
	SRAM_CE_N,
	SRAM_DQ,
	SRAM_LB_N,
	SRAM_OE_N,
	SRAM_UB_N,
	SRAM_WE_N,

	//////////// Flash //////////
	FL_ADDR,
	FL_CE_N,
	FL_DQ,
	FL_OE_N,
	FL_RST_N,
	FL_RY,
	FL_WE_N,
	FL_WP_N,

	//////////// GPIO, GPIO connect to D5M - 5M Pixel Camera //////////
	D5M_D,
	D5M_FVAL,
	D5M_LVAL,
	D5M_PIXLCLK,
	D5M_RESET_N,
	D5M_SCLK,
	D5M_SDATA,
	D5M_STROBE,
	D5M_TRIGGER,
	D5M_XCLKIN 
);

//=======================================================
//  PARAMETER declarations
//=======================================================


//=======================================================
//  PORT declarations
//=======================================================

//////////// CLOCK //////////
input		          		CLOCK_50;
input		          		CLOCK2_50;
input		          		CLOCK3_50;

//////////// Sma //////////
input		          		SMA_CLKIN;
output		          		SMA_CLKOUT;

//////////// LED //////////
output		     [8:0]		LEDG;
output		    [17:0]		LEDR;

//////////// KEY //////////
input		     [3:0]		KEY;

//////////// EJTAG //////////
inout		     [6:0]		EX_IO;

//////////// SW //////////
input		    [17:0]		SW;

//////////// SEG7 //////////
output		     [6:0]		HEX0;
output		     [6:0]		HEX1;
output		     [6:0]		HEX2;
output		     [6:0]		HEX3;
output		     [6:0]		HEX4;
output		     [6:0]		HEX5;
output		     [6:0]		HEX6;
output		     [6:0]		HEX7;

//////////// LCD //////////
output		          		LCD_BLON;
inout		     [7:0]		LCD_DATA;
output		          		LCD_EN;
output		          		LCD_ON;
output		          		LCD_RS;
output		          		LCD_RW;

//////////// RS232 //////////
output		          		UART_CTS;
input		          		UART_RTS;
input		          		UART_RXD;
output		          		UART_TXD;

//////////// PS2 for Keyboard and Mouse //////////
inout		          		PS2_CLK;
inout		          		PS2_CLK2;
inout		          		PS2_DAT;
inout		          		PS2_DAT2;

//////////// SDCARD //////////
output		          		SD_CLK;
inout		          		SD_CMD;
inout		     [3:0]		SD_DAT;
input		          		SD_WP_N;

//////////// VGA //////////
output		     [7:0]		VGA_B;
output		          		VGA_BLANK_N;
output		          		VGA_CLK;
output		     [7:0]		VGA_G;
output		          		VGA_HS;
output		     [7:0]		VGA_R;
output		          		VGA_SYNC_N;
output		          		VGA_VS;

//////////// Audio //////////
input		          		AUD_ADCDAT;
inout		          		AUD_ADCLRCK;
inout		          		AUD_BCLK;
output		          		AUD_DACDAT;
inout		          		AUD_DACLRCK;
output		          		AUD_XCK;

//////////// I2C for EEPROM //////////
output		          		EEP_I2C_SCLK;
inout		          		EEP_I2C_SDAT;

//////////// I2C for Audio Tv-Decoder  //////////
output		          		I2C_SCLK;
inout		          		I2C_SDAT;

//////////// Ethernet 0 //////////
output		          		ENET0_GTX_CLK;
input		          		ENET0_INT_N;
input		          		ENET0_LINK100;
output		          		ENET0_MDC;
inout		          		ENET0_MDIO;
output		          		ENET0_RST_N;
input		          		ENET0_RX_CLK;
input		          		ENET0_RX_COL;
input		          		ENET0_RX_CRS;
input		     [3:0]		ENET0_RX_DATA;
input		          		ENET0_RX_DV;
input		          		ENET0_RX_ER;
input		          		ENET0_TX_CLK;
output		     [3:0]		ENET0_TX_DATA;
output		          		ENET0_TX_EN;
output		          		ENET0_TX_ER;
input		          		ENETCLK_25;

//////////// Ethernet 1 //////////
output		          		ENET1_GTX_CLK;
input		          		ENET1_INT_N;
input		          		ENET1_LINK100;
output		          		ENET1_MDC;
inout		          		ENET1_MDIO;
output		          		ENET1_RST_N;
input		          		ENET1_RX_CLK;
input		          		ENET1_RX_COL;
input		          		ENET1_RX_CRS;
input		     [3:0]		ENET1_RX_DATA;
input		          		ENET1_RX_DV;
input		          		ENET1_RX_ER;
input		          		ENET1_TX_CLK;
output		     [3:0]		ENET1_TX_DATA;
output		          		ENET1_TX_EN;
output		          		ENET1_TX_ER;

//////////// TV Decoder //////////
input		          		TD_CLK27;
input		     [7:0]		TD_DATA;
input		          		TD_HS;
output		          		TD_RESET_N;
input		          		TD_VS;

//////////// USB 2.0 OTG //////////
output		     [1:0]		OTG_ADDR;
output		          		OTG_CS_N;
output		     [1:0]		OTG_DACK_N;
inout		    [15:0]		OTG_DATA;
input		     [1:0]		OTG_DREQ;
inout		          		OTG_FSPEED;
input		     [1:0]		OTG_INT;
inout		          		OTG_LSPEED;
output		          		OTG_RD_N;
output		          		OTG_RST_N;
output		          		OTG_WE_N;

//////////// IR Receiver //////////
input		          		IRDA_RXD;

//////////// SDRAM //////////
output		    [12:0]		DRAM_ADDR;
output		     [1:0]		DRAM_BA;
output		          		DRAM_CAS_N;
output		          		DRAM_CKE;
output		          		DRAM_CLK;
output		          		DRAM_CS_N;
inout		    [31:0]		DRAM_DQ;
output		     [3:0]		DRAM_DQM;
output		          		DRAM_RAS_N;
output		          		DRAM_WE_N;

//////////// SRAM //////////
output		    [19:0]		SRAM_ADDR;
output		          		SRAM_CE_N;
inout		    [15:0]		SRAM_DQ;
output		          		SRAM_LB_N;
output		          		SRAM_OE_N;
output		          		SRAM_UB_N;
output		          		SRAM_WE_N;

//////////// Flash //////////
output		    [22:0]		FL_ADDR;
output		          		FL_CE_N;
inout		     [7:0]		FL_DQ;
output		          		FL_OE_N;
output		          		FL_RST_N;
input		          		FL_RY;
output		          		FL_WE_N;
output		          		FL_WP_N;

//////////// GPIO, GPIO connect to D5M - 5M Pixel Camera //////////
input		    [11:0]		D5M_D;
input		          		D5M_FVAL;
input		          		D5M_LVAL;
input		          		D5M_PIXLCLK;
output		          		D5M_RESET_N;
output		          		D5M_SCLK;
inout		          		D5M_SDATA;
input		          		D5M_STROBE;
output		          		D5M_TRIGGER;
output		          		D5M_XCLKIN;


//=======================================================
//  REG/WIRE declarations
//=======================================================
wire	[15:0]	Read_DATA1;
wire	[15:0]	Read_DATA2;

wire	[11:0]	mCCD_DATA;
wire			mCCD_DVAL;
wire			mCCD_DVAL_d;
wire	[15:0]	X_Cont;
wire	[15:0]	Y_Cont;
reg [15:0] X_Cont_d1;
reg [15:0] Y_Cont_d1;

always @(posedge D5M_PIXLCLK or negedge DLY_RST_1)
begin
    if (!DLY_RST_1)
    begin
        X_Cont_d1 <= 16'd0;
        Y_Cont_d1 <= 16'd0;
    end
    else
    begin
        X_Cont_d1 <= X_Cont;
        Y_Cont_d1 <= Y_Cont;
    end
end

wire	[9:0]	X_ADDR;
wire	[31:0]	Frame_Cont;
wire			DLY_RST_0;
wire			DLY_RST_1;
wire			DLY_RST_2;
wire			DLY_RST_3;
wire			DLY_RST_4;
wire			Read;
reg		[11:0]	rCCD_DATA;
reg				rCCD_LVAL;
reg				rCCD_FVAL;
wire	[11:0]	sCCD_R;
wire	[11:0]	sCCD_G;
wire	[11:0]	sCCD_B;
wire			sCCD_DVAL;
// New hand pipeline: 800x600 -> 160x120, analysis on CLOCK2_50.
wire skin_pixel;
wire [11:0] processed_R,processed_G,processed_B;
wire hand_cam_rst_n,hand_analysis_rst_n;
wire VGA_CTRL_CLK;
wire sample_valid,sample_skin,hand_frame_start;
wire [7:0] sample_x,sample_y;
wire [15:0] hand_rgb_x,hand_rgb_y;
wire [3:0] hand_count,hand_raw_count,hand_error,hand_support;
wire hand_display_valid,hand_raw_valid,hand_present,hand_done,hand_busy,hand_waiting;
wire [7:0] hand_palm_x,hand_palm_y,hand_radius,hand_wrist_x,hand_wrist_y;
wire [6:0] hand_tip0,hand_tip1,hand_tip2,hand_tip3,hand_tip4;
wire [39:0] hand_debug;
wire [6:0] hex_count,hex_raw,hex_error,hex_support;
wire processed_valid,capture_rst_n,vga_rst_n;
wire			sdram_ctrl_clk;
wire	[9:0]	oVGA_R;   				
wire	[9:0]	oVGA_G;	 				
wire	[9:0]	oVGA_B;   				
wire [15:0] VGA_X;
wire [15:0] VGA_Y;
//power on start
wire             auto_start;
//=======================================================
//  Structural coding
//=======================================================
// D5M
assign	D5M_TRIGGER	=	1'b1;  // tRIGGER
assign	D5M_RESET_N	=	DLY_RST_1;
assign  VGA_CTRL_CLK = ~VGA_CLK;

assign LEDR = SW;
assign LEDG = {hand_display_valid,hand_raw_valid,hand_present,hand_busy,hand_error,hand_waiting};
assign	UART_TXD = UART_RXD;

assign VGA_R=oVGA_R[9:2];
assign VGA_G=oVGA_G[9:2];
assign VGA_B=oVGA_B[9:2];
hand_overlay u_hand_overlay(
	.clk(D5M_PIXLCLK),
	.rst_n(hand_cam_rst_n),
   .red(sCCD_R),
	.green(sCCD_G),
	.blue(sCCD_B),
	.rgb_valid(sCCD_DVAL),
	.skin(skin_pixel),
   .binary_mode(SW[17]),
	.debug_mode(SW[15]),
	.scaled_x(sample_x),
	.scaled_y(sample_y),
	.debug_data(hand_debug),
   .out_red(processed_R),
	.out_green(processed_G),
	.out_blue(processed_B),
	.out_valid(processed_valid)
);

hand_reset_sync u_capture_reset(
	.clk(~D5M_PIXLCLK),
	.arst_n(DLY_RST_2&&KEY[0]),
	.rst_n(capture_rst_n)
);

hand_reset_sync u_vga_reset(
	.clk(VGA_CTRL_CLK),
	.arst_n(DLY_RST_2&&KEY[0]),
	.rst_n(vga_rst_n)
);

//D5M read 
always@(posedge D5M_PIXLCLK)
begin
	rCCD_DATA	<=	D5M_D;
	rCCD_LVAL	<=	D5M_LVAL;
	rCCD_FVAL	<=	D5M_FVAL;
end

//auto start when power on
(* altera_attribute="-name SYNCHRONIZER_IDENTIFICATION FORCED" *) reg [2:0] auto_start_sync;
always @(negedge D5M_PIXLCLK or negedge capture_rst_n)
    if(!capture_rst_n) auto_start_sync<=0;
    else auto_start_sync<={auto_start_sync[1:0],(KEY[0]&&DLY_RST_3&&!DLY_RST_4)};
assign auto_start=auto_start_sync[2];
//Reset module
Reset_Delay			u2	(	
							.iCLK(CLOCK2_50),
							.iRST(KEY[0]),
							.oRST_0(DLY_RST_0),
							.oRST_1(DLY_RST_1),
							.oRST_2(DLY_RST_2),
							.oRST_3(DLY_RST_3),
							.oRST_4(DLY_RST_4)
						);
//D5M image capture
CCD_Capture			u3	(	
							.oDATA(mCCD_DATA),
							.oDVAL(mCCD_DVAL),
							.oX_Cont(X_Cont),
							.oY_Cont(Y_Cont),
							.oFrame_Cont(Frame_Cont),
							.iDATA(rCCD_DATA),
							.iFVAL(rCCD_FVAL),
							.iLVAL(rCCD_LVAL),
							.iSTART(!KEY[3]|auto_start),
							.iEND(1'b0),
							.iCLK(~D5M_PIXLCLK),
							.iRST(capture_rst_n)
						);

		
//D5M raw date convert to RGB data
`ifdef VGA_640x480p60
RAW2RGB				u4	(	
							.iCLK(D5M_PIXLCLK),
							.iRST(hand_cam_rst_n),
							.iDATA(mCCD_DATA),
							.iDVAL(mCCD_DVAL),
							.oRed(sCCD_R),
							.oGreen(sCCD_G),
							.oBlue(sCCD_B),
							.oDVAL(sCCD_DVAL),
							.iX_Cont(X_Cont),
							.iY_Cont(Y_Cont)
						);
`else
RAW2RGB				u4	(	
							.iCLK(D5M_PIXLCLK),
							.iRST_n(hand_cam_rst_n),
							.iData(mCCD_DATA),
							.iDval(mCCD_DVAL),
							.oRed(sCCD_R),
							.oGreen(sCCD_G),
							.oBlue(sCCD_B),
							.oDval(sCCD_DVAL),
							.iZoom(SW[16]),
							.iX_Cont(X_Cont),
							.iY_Cont(Y_Cont)
						);
`endif


// Existing skin threshold is retained.
skin_detect u_skin_detect(
	 .iRed(sCCD_R),
	 .iGreen(sCCD_G),
	 .iBlue(sCCD_B),
    .iDVAL(sCCD_DVAL),
	 .oSkin(skin_pixel)
	);
	
hand_stream_adapter u_hand_stream(
	 .clk(D5M_PIXLCLK),
	 .rst_n(hand_cam_rst_n),
    .raw_x(X_Cont),
	 .raw_y(Y_Cont),
	 .frame_id(Frame_Cont),
	 .rgb_valid(sCCD_DVAL),
	 .skin(skin_pixel),
    .sample_valid(sample_valid),
	 .sample_skin(sample_skin),
	 .sample_x(sample_x),
	 .sample_y(sample_y),
    .frame_start(hand_frame_start),
	 .rgb_x(hand_rgb_x),
	 .rgb_y(hand_rgb_y)
);

hand_pipeline u_hand(
	 .cam_clk(D5M_PIXLCLK),
	 .analysis_clk(CLOCK2_50),
	 .arst_n(DLY_RST_1&&KEY[0]),
    .frame_start(hand_frame_start),
	 .sample_valid(sample_valid),
	 .sample_skin(sample_skin),
    .sample_x(sample_x),
	 .sample_y(sample_y),
	 .stable_count(hand_count),
	 .raw_count(hand_raw_count),
    .error(hand_error),
	 .support(hand_support),
	 .display_valid(hand_display_valid),
	 .raw_valid(hand_raw_valid),
    .present(hand_present),
	 .result_done(hand_done),
	 .busy(hand_busy),
	 .camera_waiting(hand_waiting),
    .palm_x(hand_palm_x),
	 .palm_y(hand_palm_y),
	 .palm_radius(hand_radius),
    .wrist_x(hand_wrist_x),
	 .wrist_y(hand_wrist_y),
    .tip0(hand_tip0),
	 .tip1(hand_tip1),
	 .tip2(hand_tip2),
	 .tip3(hand_tip3),
	 .tip4(hand_tip4),
    .analysis_rst_n(hand_analysis_rst_n),
	 .cam_rst_n(hand_cam_rst_n)
);

hand_debug_mailbox u_hand_debug(
	 .source_clk(CLOCK2_50),
	 .source_rst_n(hand_analysis_rst_n),
    .update(hand_done),
	 .source_data({hand_raw_valid,hand_present,6'd0,hand_radius,hand_palm_y,hand_palm_x,hand_error,4'd0}),
    .dest_clk(D5M_PIXLCLK),
	 .dest_rst_n(hand_cam_rst_n),
	 .dest_data(hand_debug)
);

SEG7_LUT u_hex_count(hex_count,hand_count);
SEG7_LUT u_hex_raw(hex_raw,hand_raw_count);
SEG7_LUT u_hex_error(hex_error,hand_error);
SEG7_LUT u_hex_support(hex_support,hand_support);
assign HEX0=hand_display_valid?hex_count:7'b0000110; // E = no reliable result yet
assign HEX1=SW[14]?hex_raw:7'h7f;
assign HEX2=SW[14]?hex_error:7'h7f;
assign HEX3=SW[14]?hex_support:7'h7f;
assign HEX4=7'h7f;assign HEX5=7'h7f;assign HEX6=7'h7f;assign HEX7=7'h7f;

sdram_pll 			u6	(
							.inclk0(CLOCK2_50),
							.c0(sdram_ctrl_clk),
							.c1(DRAM_CLK),
							.c2(D5M_XCLKIN), //25M
`ifdef VGA_640x480p60
							.c3(VGA_CLK)     //25M 
`else
						    .c4(VGA_CLK)     //40M 	
`endif
						);

//SDRam Read and Write as Frame Buffer
// ============================================================
// SDRAM Read / Write Frame Buffer
// ============================================================

// ============================================================
// SDRAM Read / Write Frame Buffer
// ============================================================

Sdram_Control u7 (
                            // HOST Side
                            .RESET_N(KEY[0]),
                            .CLK(sdram_ctrl_clk),

                            // =================================================
                            // FIFO Write Side 1
                            // =================================================

                            .WR1_DATA({
                                1'b0,
                                processed_G[11:7],
                                processed_B[11:2]
                            }),

                            // Only write when LIVE / capturing frame
                            .WR1(
                                processed_valid
                            ),

                            .WR1_ADDR(0),

`ifdef VGA_640x480p60

                            .WR1_MAX_ADDR(640*480/2),
                            .WR1_LENGTH(8'h50),

`else

                            .WR1_MAX_ADDR(800*600/2),
                            .WR1_LENGTH(8'h80),

`endif

                            .WR1_LOAD(!DLY_RST_0),
                            .WR1_CLK(D5M_PIXLCLK),


                            // =================================================
                            // FIFO Write Side 2
                            // =================================================

                            .WR2_DATA({
                                1'b0,
                                processed_G[6:2],
                                processed_R[11:2]
                            }),

                            // Same freeze control as WR1
                            .WR2(
                                processed_valid
                            ),

                            .WR2_ADDR(23'h100000),

`ifdef VGA_640x480p60

                            .WR2_MAX_ADDR(
                                23'h100000 +
                                640*480/2
                            ),

                            .WR2_LENGTH(8'h50),

`else

                            .WR2_MAX_ADDR(
                                23'h100000 +
                                800*600/2
                            ),

                            .WR2_LENGTH(8'h80),

`endif

                            .WR2_LOAD(!DLY_RST_0),
                            .WR2_CLK(D5M_PIXLCLK),


                            // =================================================
                            // FIFO Read Side 1
                            //
                            // VGA keeps reading even when writing is frozen.
                            // =================================================

                            .RD1_DATA(Read_DATA1),

                            .RD1(Read),

                            .RD1_ADDR(0),

`ifdef VGA_640x480p60

                            .RD1_MAX_ADDR(
                                640*480/2
                            ),

                            .RD1_LENGTH(8'h50),

`else

                            .RD1_MAX_ADDR(
                                800*600/2
                            ),

                            .RD1_LENGTH(8'h80),

`endif

                            .RD1_LOAD(!DLY_RST_0),

                            .RD1_CLK(
                                ~VGA_CTRL_CLK
                            ),


                            // =================================================
                            // FIFO Read Side 2
                            // =================================================

                            .RD2_DATA(Read_DATA2),

                            .RD2(Read),

                            .RD2_ADDR(
                                23'h100000
                            ),

`ifdef VGA_640x480p60

                            .RD2_MAX_ADDR(
                                23'h100000 +
                                640*480/2
                            ),

                            .RD2_LENGTH(8'h50),

`else

                            .RD2_MAX_ADDR(
                                23'h100000 +
                                800*600/2
                            ),

                            .RD2_LENGTH(8'h80),

`endif

                            .RD2_LOAD(!DLY_RST_0),

                            .RD2_CLK(
                                ~VGA_CTRL_CLK
                            ),


                            // =================================================
                            // SDRAM Physical Interface
                            // =================================================

                            .SA(DRAM_ADDR),

                            .BA(DRAM_BA),

                            .CS_N(DRAM_CS_N),

                            .CKE(DRAM_CKE),

                            .RAS_N(DRAM_RAS_N),

                            .CAS_N(DRAM_CAS_N),

                            .WE_N(DRAM_WE_N),

                            .DQ(DRAM_DQ),

                            .DQM(DRAM_DQM)
                        );
//D5M I2C control
I2C_CCD_Config 		u8	(	//	Host Side
							.iCLK(CLOCK2_50),
							.iRST_N(DLY_RST_2),
							.iEXPOSURE_ADJ(KEY[1]),
							.iEXPOSURE_DEC_p(SW[0]),
							.iZOOM_MODE_SW(SW[16]),
							//	I2C Side
							.I2C_SCLK(D5M_SCLK),
							.I2C_SDAT(D5M_SDATA)
						);
//VGA DISPLAY
VGA_Controller		u1	(	//	Host Side
							.oRequest(Read),
							.iRed(Read_DATA2[9:0]),
							.iGreen({Read_DATA1[14:10],Read_DATA2[14:10]}),
							.iBlue(Read_DATA1[9:0]),
							//	VGA Side
							.oVGA_X(VGA_X),
                     .oVGA_Y(VGA_Y),
							.oVGA_R(oVGA_R),
							.oVGA_G(oVGA_G),
							.oVGA_B(oVGA_B),
							.oVGA_H_SYNC(VGA_HS),
							.oVGA_V_SYNC(VGA_VS),
							.oVGA_SYNC(VGA_SYNC_N),
							.oVGA_BLANK(VGA_BLANK_N),
							//	Control Signal
							.iCLK(VGA_CTRL_CLK),
							.iRST_N(vga_rst_n),
							.iZOOM_MODE_SW(SW[16])
						);

endmodule

